version: "3"

services:
  redis:
    image: redis:5.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/redis

  mongo:
    container_name: mongo
    image: mongo:4.0.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: --smallfiles

volumes:
  redis-data:
  mongo-data:
